---
cloud_service_group: Networking
cloud_service_type: VPCGateway
name: Count by Region
query:
  aggregate:
    - group:
        keys:
          - key: data.region
            name: Region
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0
