name: VPC Gateway Count by Project
version: '1.0'
description: Count VPC Gateways by project
default_chart_type: DONUT
default_chart_options:
  show_legend: true
  legend_position: right
dimensions:
  - key: account
    name: Project
  - key: data.gateway_type
    name: Gateway Type
fields:
  - key: _id
    name: Count
    operator: count
