---
cloud_service_group: AppEngine
cloud_service_type: Instance
name: Total Memory Usage
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: sum
            key: data.instance.memory_usage
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: MB
