---
cloud_service_group: Datastore
cloud_service_type: Namespace
name: Count by Kind Count
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.kind_count
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT 