---
cloud_service_group: Batch
cloud_service_type: Location
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0
