a = {
    'name': 'projects/bluese-cloudone-20200113/locations/us-central1/functions/function-3-pubsub',
    'buildConfig': {'build': 'projects/286919713412/locations/us-central1/builds/7c8bcc20-c9ad-49a9-8604-d31f40d67c72',
                    'runtime': 'nodejs16',
                    'entryPoint': 'helloPubSub',
                    'source': {
                        'storageSource': {'bucket': 'gcf-v2-sources-286919713412-us-central1',
                                          'object': 'function-3-pubsub/function-source.zip'}},
                    'environmentVariables': {'A': '111'},
                    'sourceProvenance': {'resolvedStorageSource': {'bucket': 'gcf-v2-sources-286919713412-us-central1',
                                                                   'object': 'function-3-pubsub/function-source.zip',
                                                                   'generation': '1668404401565036'}}},
    'serviceConfig': {'service': 'projects/bluese-cloudone-20200113/locations/us-central1/services/function-3-pubsub',
                      'timeoutSeconds': 60,
                      'environmentVariables': {'type': 'test', 'env': 'prd', 'a': 'b'},
                      'maxInstanceCount': 10,
                      'ingressSettings': 'ALLOW_INTERNAL_ONLY',
                      'uri': 'https://function-3-pubsub-ljh3gqne4q-uc.a.run.app',
                      'serviceAccountEmail': '286919713412-compute@developer.gserviceaccount.com',
                      'availableMemory': '128Mi',
                      'allTrafficOnLatestRevision': True,
                      'revision': 'function-3-pubsub-00001-kif'},
    'eventTrigger': {
        'trigger': 'projects/bluese-cloudone-20200113/locations/us-central1/triggers/function-3-pubsub-215536',
        'triggerRegion': 'us-central1',
        'eventType': 'google.cloud.pubsub.topic.v1.messagePublished',
        'pubsubTopic': 'projects/bluese-cloudone-20200113/topics/duration-test',
        'serviceAccountEmail': '286919713412-compute@developer.gserviceaccount.com',
        'retryPolicy': 'RETRY_POLICY_DO_NOT_RETRY'},
    'state': 'ACTIVE',
    'updateTime': '2022-11-14T05:41:09.230964501Z',
    'labels': {'deployment-tool': 'console-cloud'},
    'environment': 'GEN_2'
}

b = {'name': 'projects/bluese-cloudone-20200113/locations/us-central1/functions/function-1',
     'buildConfig': {'build': 'projects/286919713412/locations/us-central1/builds/c85646e4-3372-4d59-a0a7-4668b5fbd243',
                     'runtime': 'python38',
                     'entryPoint': 'hello_http',
                     'source': {
                         'storageSource': {'bucket': 'gcf-v2-sources-286919713412-us-central1',
                                           'object': 'function-1/function-source.zip'}},
                     'sourceProvenance': {
                         'resolvedStorageSource': {'bucket': 'gcf-v2-sources-286919713412-us-central1',
                                                   'object': 'function-1/function-source.zip',
                                                   'generation': '1667085967211367'}}},
     'serviceConfig': {'service': 'projects/bluese-cloudone-20200113/locations/us-central1/services/function-1',
                       'timeoutSeconds': 60,
                       'maxInstanceCount': 1000,
                       'ingressSettings': 'ALLOW_ALL',
                       'uri': 'https://function-1-ljh3gqne4q-uc.a.run.app',
                       'serviceAccountEmail': '286919713412-compute@developer.gserviceaccount.com',
                       'availableMemory': '128Mi',
                       'allTrafficOnLatestRevision': True,
                       'revision': 'function-1-00001-pul'},
     'state': 'ACTIVE',
     'updateTime': '2022-10-29T23:27:24.235871818Z',
     'labels': {'deployment-tool': 'console-cloud'},
     'environment': 'GEN_2'}
