---
metric_id: metric-google-cloud-kms-keyring-count-by-region
name: Count by Region
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.KMS.KeyRing
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
      default: true
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-kms-keyring
version: '1.0'
