from .cluster import CLOUD_SERVICE_TYPES as CLUSTER_CLOUD_SERVICE_TYPES
from .node_pool import CLOUD_SERVICE_TYPES as NODE_POOL_CLOUD_SERVICE_TYPES

CLOUD_SERVICE_TYPES = (
    CLUSTER_CLOUD_SERVICE_TYPES + 
    NODE_POOL_CLOUD_SERVICE_TYPES
)