---
cloud_service_group: "Pub/Sub"
cloud_service_type: Snapshot
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0