---
cloud_service_group: AppEngine
cloud_service_type: Application
name: Count By Serving Status
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.application.serving_status
        fields:
          - name: value
            operator: count
options:
  chart_type: PIE
  name_options:
    key: name
