---
cloud_service_group: ComputeEngine
cloud_service_type: Instance
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.hardware.memory
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB