key: vpc_gateway_count_by_region
name: VPC Gateway Count by Region
unit:
  x: "count"
  y: "count"
chart_type: COLUMN
filters:
  - name: "Gateway Type"
    key: data.gateway_type
    options:
      - "NAT_GATEWAY"
      - "VPN_GATEWAY"
      - "TARGET_VPN_GATEWAY"
query:
  metric_query:
    conditions:
      - key: "cloud_service_type"
        value: "VPCGateway"
        operator: "eq"
    aggregate:
      group:
        keys:
          - key: data.region
            name: "Region"
          - key: data.gateway_type
            name: "Gateway Type"
        fields:
          - operator: count
            key: _id
            name: "count"
