---
metric_id: metric-gcp-computeengine-instance-count
name: Instance Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.ComputeEngine.Instance
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: instance_type
      name: Instance Type
      search_key: instance_type
    - key: data.compute.instance_state
      name: Instance State
      search_key: data.compute.instance_state
      default: true
    - key: data.os.os_type
      name: OS Type
      search_key: data.os.os_type
    - key: data.compute.az
      name: Availability Zone
      search_key: data.compute.az
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-gcp-computeengine-instance
version: '1.0'