from spaceone.inventory.model.bigquery import *
from spaceone.inventory.model.cloud_sql import *
from spaceone.inventory.model.disk import *
from spaceone.inventory.model.external_ip_address import *
from spaceone.inventory.model.firewall import *
from spaceone.inventory.model.health_check import *
from spaceone.inventory.model.instance_group import *
from spaceone.inventory.model.instance_template import *
from spaceone.inventory.model.load_balancing import *
from spaceone.inventory.model.machine_image import *
from spaceone.inventory.model.route import *
from spaceone.inventory.model.snapshot import *
from spaceone.inventory.model.storage import *
from spaceone.inventory.model.vpc_network import *
