---
metric_id: metric-google-cloud-batch-location-count
name: Location Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Batch.Location
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.location_id
      name: Location ID
      search_key: data.location_id
      default: true
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-batch-location
version: '1.0'
