---
metric_id: metric-google-cloud-datastore-index-count
name: Index Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Datastore.Index
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.kind
      name: Kind
      search_key: data.kind
      default: true
    - key: data.state
      name: State
      search_key: data.state
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-datastore-index
version: '1.1' 