---
name: index_count
key: datastore_index_count
unit:
  x: Count
  y: Count
chart_type: COLUMN
query:
  resource_type: inventory.CloudService
  query:
    aggregate:
      - group:
          keys:
            - name: project_id
              key: account
            - name: kind
              key: data.kind
          fields:
            - name: index_count
              operator: count
              key: cloud_service_id
    filter:
      - key: cloud_service_type
        value: Index
        operator: eq
      - key: cloud_service_group
        value: Datastore
        operator: eq 

dimensions:
- name: project_id
  key: data.project_id
- name: kind
  key: data.kind
- name: state
  key: data.state 