---
metric_id: metric-google-cloud-firebase-app-count
name: App Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.Firebase.App
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.platform
      name: Platform
      search_key: data.platform
      default: true
    - key: data.state
      name: State
      search_key: data.state
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-firebase-app
version: '1.0'
