---
cloud_service_group: CloudRun
cloud_service_type: Service
name: Count by Project
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
