---
metric_id: metric-google-cloud-storage-transfer-job-count
name: Transfer Job Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.StorageTransfer.TransferJob
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
    - key: data.status
      name: Status
      search_key: data.status
      default: true
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-storage-transfer-job
version: '1.1' 