---
metric_id: metric-google-cloud-cloudbuild-worker_pool-count
name: WorkerPool Count
metric_type: GAUGE
resource_type: inventory.CloudService:google_cloud.CloudBuild.WorkerPool
query_options:
  group_by:
    - key: region_code
      name: Region
      search_key: region_code
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: account
      name: Project ID
      search_key: account
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-google-cloud-cloudbuild-worker_pool
version: '1.1'
