---
cloud_service_group: CloudBuild
cloud_service_type: Build
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0
