---
cloud_service_group: Firestore
cloud_service_type: Database
name: Count by Project
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: COLUMN
  name_options:
    key: name 